#!/bin/bash

TAG=$1
NAME=$(basename $PWD)
if [ -z "$TAG" -o "$TAG" = -h ]; then
  echo Usage: $0 TAG
  exit 0
fi
if [ $TAG = 01 ]; then
  echo Building $NAME
  docker build --no-cache -t "$NAME:$TAG" -f dockerfile-$TAG .
else
  PLAT=linux/amd64
  echo Building $NAME:$TAG for $PLAT
  docker buildx build --platform linux/amd64 --no-cache -t "$NAME:$TAG" -f dockerfile-$TAG .
fi
