#!/bin/bash
#
# Read flags.
HELP=
UOPTS=descprod
TAG=10
while [ $# -gt 0 ]; do
  ARG=$1
  if [ ${ARG:0:2} = -- ]; then
    FLG=${ARG:2}
    shift
    echo Invalid flag $ARG
    exit 1
  elif [ ${ARG:0:1} = - ]; then
    FLG=${ARG:1}
    shift
    if [ $FLG == 'h' ]; then
      HELP=true
    elif [ $FLG == 'v' ]; then
      TAG=$1
      shift
    elif [ $FLG == 'root' ]; then
      UOPTS="--user root"
    elif [ $FLG == 'descprod' ]; then
      UOPTS="--user descprod"
    else
      echo Invalid flag $ARG
      exit 1
    fi
  else
    break
  fi
done

NAME=$(basename $(pwd))

if [ -n "$HELP" ]; then
  echo Usage: $0 [-h] [-v TAG] [-root] [-descprod] COPTS
  echo "  TAG is the $NAME image version."
  echo "  -root to run container as root"
  echo "  COPTS are the arguments passed to the container"
  exit 0
fi

# Remaining arguments are passed to the container.
COPTS="$*"
if [ -z "$COPTS" ]; then
  COPTS="git-safedir update-desc-prod mysql:noaio server"
fi

FROM=$NAME:$TAG
CNAME=$NAME


# Configure mounts.
DATDIR=$HOME/desc/dpvol01
LOCDIR=$HOME/desc/dpvol02
MSQDIR=$HOME/desc/dpvol03
MOUNT_DATA="-v $DATDIR:/mnt/dpvol01"
#MOUNT_MYSQL="-v $MSQDIR:/mnt/dpvol03"
#MOUNT_MYSQL="-v $MSQDIR/mysql:/var/lib/mysql"
MOUNT_MYSQL="-v mysql:/var/lib/mysql"
MOUNT_LOCAL=
for ARG in $COPTS; do
  if [ $ARG = server ]; then
    MOUNT_LOCAL="-v $LOCDIR:/mnt/dpvol02"
  fi
done

echo "*************************************************************************************************"
echo Starting container $CNAME with image $FROM
echo "    User opts: $UOPTS"
echo "  Local mount: $MOUNT_LOCAL"
echo "  MySQL mount: $MOUNT_MYSQL"
echo "  Server opts: $COPTS"
echo "*************************************************************************************************"
COM="docker run --name $CNAME --rm -p 88:5000 -p 8888:8888 $MOUNT_DATA $MOUNT_LOCAL $MOUNT_MYSQL $UOPTS -it $FROM $COPTS"
echo "Command: $COM"
echo
echo
$COM

