#!/usr/bin/env python3

# runapp-pmb
#
# David Adams
# April 2023
#
# Descprod application wrapper for pmb.
# Usage runapp-pmb NAME CONFIG HOWFIG
#     NAME - The final descprod application name.
#   CONFIG - The config for that application
#   HOWFIG - The howfig (how configuration)
# The howfig is a series of dash-separated fields. The first of these must begin
# with "pmb:" 
# First argument is a config string whose first field must start with "pmb:".
# Remaining arguments are the command to run in batch.

import os
import sys
import subprocess

this = os.path.basename(sys.argv[0])

STALOG=current-status.txt
MYNAME=$(basename $0)

function myecho() {
  echo $MYNAME: $*
  echo $MYNAME: $* >$STALOG
}

def myexit(rc, msg):
    print(f"{this}: {msg}")
    exit(rc)

jmap = json.load(open('config.json'))
jobtype = jmap['jobtype']
config  = jmap['config']
howfig  = jmap['howfig']

ipos = howfig.find(',')
pmbcfg = howfig[0:ipos]
howrem = howfig[ipos+1:]

pmbcom = f"runapp-{jobtype} {config} {howrem}"
pmb-wrap pmbcfg pmbcom
JOBID=$(cat batch_id.dat)
while true; do
    SLIN="$(sqs --job $JOBID)"
    if [ -z "$SLIN" ]; then break; fi
    echo $SLIN
done
