#!/bin/bash

# Add a user account.

UNAM=$1 
GNAM=$2
if [ -n "$GNAM" ]; then
  GFLG="--ingroup $GNAM"
else
  GFLG=
fi
UHOM=/users/$UNAM

UINFO=$(getent passwd $UNAM)
if [ -n "$UINFO" ]; then
  echo User already exists: $UINFO
else
  if ! sudo adduser $UNAM $GFLG --home $UHOM --disabled-password --gecos ''; then
    echo Unable to add user $UNAM
    exit 2
  fi
fi
