#!/bin/bash

# Add a user account.

UNAM=$1 
UIDVAL=$2
UIDOPT=
if [ -n "$UIDVAL" ]; then
  UIDOPT="--uid $UIDVAL"
fi
UHOM=/users/$UNAM

UINFO=$(getent passwd $UNAM)
if [ -n "$UINFO" ]; then
  echo User already exists: $UINFO
else
  if ! sudo adduser --home $UHOM $UIDOPT --disabled-password --gecos '' --ingroup users $UNAM; then
    echo Unable to add user $UNAM
    exit 2
  fi
fi
