#!/bin/bash

# descprod-next-jobid
#
# David Adams
# November 2022
#
# Advance the job ID and return it.

MYNAME=$(basename $0)
JIDFIL=$HOME/data/etc/jobid.txt
JOBID=jobid-not-found
if ! ls ${JIDFIL}* 2>/dev/null >/dev/null; then
  echo $MYNAME: ERROR: Job ID file not found: $JIDFIL >&2
  echo $JOBID
  exit 1
fi
COUNT=0
TMPFIL=$(mktemp ${JIDFIL}-pid$$-XXXXXX)
while [ $COUNT -lt 20 ]; do
  if mv $JIDFIL $TMPFIL 2>/dev/null; then
    JOBID=$(cat $TMPFIL)
    JOBID=$((JOBID+1))
    chmod +w $TMPFIL
    echo $JOBID >$TMPFIL
    chmod -w $TMPFIL
    mv $TMPFIL $JIDFIL
    echo $JOBID
    exit 0
  fi
  sleep 1
  COUNT=$((COUNT+1))
done
rm $TMPFIL
echo $MYNAME: ERROR: Job ID file is locked: ${JIDFIL}*
echo $JOBID
exit 2

