#!/bin/bash

# Install and configure a desc-prod web server.

linkit() {
  FROM=$1
  TO=$2/$(basename $FROM)
  if [ ! -r $TO ]; then
    ln -s $FROM $TO
  fi
}

copyit() {
  FROM=$1
  TO=$2/$(basename $FROM)
  if [ ! -r $TO ]; then
    ln -s $FROM $TO
  fi
}

# Make sure we are in a descprod server.
USER=$(whoami)
if [ $USER != descprod ]; then
  echo User is $USER instead of descprod. Exiting.
  exit 1
fi

# Make sure the bin directory exists.
BINDIR=$HOME/bin
if [ ! -r $BINDIR ]; then mkdir $BINDIR; fi

# Update the desc-prod package.
PKGDIR=$HOME/dev/desc-prod
SRCDIR=$PKGDIR/server
TSTDIR=$PKGDIR/test
cd $PKGDIR
git pull
cd $HOME

linkit $TSTDIR/run-server $BINDIR
copyit $SRCDIR/nersc-proxy $BINDIR
