#!/bin/bash

# Entry point for dptest.
THIS=$0
ARG=$1
shift
ARGS="$*"

if [ -z "$ARG" ]; then
  echo Exiting...
  exit 0
fi

echo Action is $ARG

if [ $ARG = start-ssh ]; then
  echo Starting ssh
  service ssh start

elif [ $ARG = update ]; then
  echo Updating desc-prod
  cd $HOME/dev/desc-prod
  git pull

elif [ $ARG = runcoms ]; then
  echo Starting command loop.
  REQDIR=$HOME/request
  COMFIL=$REQDIR/command
  ACTFIL=${COMFIL}-in-progress
  OUTFIL=$REQDIR/out
  RSTFIL=$REQDIR/status
  LOGFIL=$REQDIR/log
  while true; do
    if [ -r $COMFIL ]; then
      mv $COMFIL $ACTFIL
      COM="$(cat $COMFIL)"
      echo $(DATE): Executing "$COM"
      $COM 2>&1 >$OUTFIL
      RST=$?
      echo $(date): Command returned $RST
      echo $RST >$RSTFIL
      echo $RST $COM >>$LOGFIL
    fi
    sleep 5
  done

else
  echo Skipping invalid command: $ARG

fi

# Excute the next command.
$THIS $ARGS
exit $?
