#!/bin/bash

# Entry point for dptest.
THIS=$0
ARG=$1
shift
ARGS="$*"
HOMDIR=/home/descprod

if [ -z "$ARG" ]; then
  echo Exiting...
  exit 0
fi

echo Action is $ARG

if [ $ARG = start-ssh ]; then
  echo Starting ssh
  service ssh start

elif [ $ARG = update ]; then
  echo Updating desc-prod
  cd $HOMDIR/dev/desc-prod
  sudo descprod git pull

elif [ $ARG = runcoms ]; then
  REQDIR=$HOMDIR/request
  COMFIL=$REQDIR/command
  ACTFIL=${COMFIL}-in-progress
  ACTFIL=${COMFIL}-done
  OUTFIL=$REQDIR/out
  RSTFIL=$REQDIR/status
  LOGFIL=$REQDIR/log
  SHOW=true
  echo $(date): Starting command loop.
  while true; do
    if [ -n "$SHOW" ]; then echo $(date): Waiting for command at $COMFIL; fi
    SHOW=
    if [ -r $COMFIL ]; then
      mv $COMFIL $ACTFIL
      rm -f $DONFIL $OUTFIL $RSTFIL
      COM="$(cat $ACTFIL)"
      echo $(date): Executing "$COM"
      bash -c "$COM" 2>&1 >$OUTFIL
      RST=$?
      mv $ACTFIL $DONFIL
      echo $(date): Command returned $RST
      echo $RST >$RSTFIL
      echo $RST $COM >>$LOGFIL
      echo
      SHOW=true
    fi
    sleep 5
  done

else
  echo Skipping invalid command: $ARG

fi

# Excute the next command.
$THIS $ARGS
exit $?
