#!/bin/bash

# Entry point for dptest.
THIS=$0
ARG=$1
shift
ARGS="$*"

echo Action is $ARG

if [ $ARG = start-ssh ]; then
  echo Starting ssh
  service ssh start

elif [ $ARG = update ]; then
  echo Updating desc-prod
  cd $HOME/dev/desc-prod
  git pull

elif [ -n "$ARG" ];  then
  echo Skipping invalid command: $ARG

fi

if [ -n "$ARG" ]; then
  $THIS $ARGS
  exit $?
fi

COMFIL=request/command
ACTFIL=${COMFIL}-in-progress
OUTFIL=request/out
RSTFIL=request/status
LOGFIL=request/log
while true; do
  if [ -r $COMFIL ]; then
    mv $COMFIL $ACTFIL
    COM=$(cat $COMFIL)
    RCOM 2>&1 >$OUTFIL
    RST=$?
    echo $RST >$RSTFIL
    echo $RST $COM >>$LOGFIL
  fi
  sleep 5
done
