apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: '13'
    field.cattle.io/creatorId: u-6e2kljvwfb
    field.cattle.io/publicEndpoints: 'null'
    nersc.gov/collab_uids: 70781,73586,73749,75699,78540,99896
    nersc.gov/gid: '70981'
    nersc.gov/gids: 60152,57177,70981,76870,75699,96414,96719,99896
    nersc.gov/roles: user
    nersc.gov/uid: '70981'
    nersc.gov/username: heatherk
  creationTimestamp: '2023-01-05T17:02:25Z'
  generation: 67
  labels:
    cattle.io/creator: norman
    workload.user.cattle.io/workloadselector: deployment-descprod-descprod-jupyter
  name: descprod-jupyter
  namespace: descprod
  resourceVersion: '748970007'
  uid: a35b3690-ea72-48c7-9e5b-4a5bcb0e1bc5
spec:
  paused: true
  progressDeadlineSeconds: 600
  replicas: 0
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: deployment-descprod-descprod-jupyter
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      annotations:
        cattle.io/timestamp: '2023-01-11T19:50:27Z'
        field.cattle.io/ports: >-
          [[{"containerPort":8888,"dnsName":"descprod-jupyter","kind":"ClusterIP","name":"jport","protocol":"TCP","sourcePort":80}]]
        field.cattle.io/publicEndpoints: >-
          [{"addresses":["128.55.206.106"],"allNodes":true,"hostname":"jupyter.descprod.production.svc.spin.nersc.org","ingressId":"descprod:jupyter","port":80,"protocol":"HTTP","serviceId":"descprod:ingress-4cd1d1b35709a20250797116918ae52b"}]
        nersc.gov/collab_uids: 70781,73586,73749,75699,78540,99896
        nersc.gov/gid: '70981'
        nersc.gov/gids: 60152,57177,70981,76870,75699,96414,96719,99896
        nersc.gov/roles: user
        nersc.gov/uid: '70981'
        nersc.gov/username: heatherk
      creationTimestamp: null
      labels:
        workload.user.cattle.io/workloadselector: deployment-descprod-descprod-jupyter
    spec:
      containers:
        - args:
            - update-desc-prod
            - jupyter
          image: registry.hub.docker.com/dladams/descprod:01
          imagePullPolicy: Always
          name: descprod-jupyter
          ports:
            - containerPort: 8888
              name: jport
              protocol: TCP
          resources: {}
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              add:
                - CHOWN
                - DAC_OVERRIDE
                - FOWNER
                - SETGID
                - SETUID
              drop:
                - ALL
            privileged: false
            readOnlyRootFilesystem: false
            runAsNonRoot: false
          stdin: true
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          tty: true
          volumeMounts:
            - mountPath: /mnt/dpvol01
              name: dpvol1
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
        - name: dpvol1
          persistentVolumeClaim:
            claimName: dpvol01
status:
  conditions:
    - lastTransitionTime: '2023-01-11T21:15:52Z'
      lastUpdateTime: '2023-01-11T21:15:52Z'
      message: Deployment is paused
      reason: DeploymentPaused
      status: Unknown
      type: Progressing
    - lastTransitionTime: '2024-07-28T15:59:02Z'
      lastUpdateTime: '2024-07-28T15:59:02Z'
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: 'True'
      type: Available
  observedGeneration: 67
