apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: '38'
    field.cattle.io/description: DESCprod web service
    field.cattle.io/publicEndpoints: >-
      [{"addresses":["128.55.206.106"],"port":80,"protocol":"HTTP","serviceName":"descprod:ingress-e9073a6bac7260568c05a661a5b2ab37","ingressName":"descprod:www","hostname":"www.descprod.org","allNodes":true},{"addresses":["128.55.206.106"],"port":30123,"protocol":"TCP","serviceName":"descprod:descprod-nodeport","allNodes":true},{"addresses":["128.55.206.106"],"port":30124,"protocol":"TCP","serviceName":"descprod:descprod-nodeport","allNodes":true},{"addresses":["128.55.206.106"],"port":80,"protocol":"HTTP","serviceName":"descprod:ingress-abb22350363dba5b6d6a88992a852fc8","ingressName":"descprod:www","hostname":"www.descprod.production.svc.spin.nersc.org","allNodes":true}]
    nersc.gov/collab_uids: ''
    nersc.gov/gid: '96594'
    nersc.gov/gids: 60152,57177,96414,96594
    nersc.gov/roles: user
    nersc.gov/uid: '96594'
    nersc.gov/username: dladams
  creationTimestamp: '2023-09-22T18:42:04Z'
  generation: 78
  labels:
    workload.user.cattle.io/workloadselector: apps.deployment-descprod-descprod
  name: descprod
  namespace: descprod
  resourceVersion: '550675780'
  selfLink: /apis/apps/v1/namespaces/descprod/deployments/descprod
  uid: fdbbef32-ce24-40be-bea8-62f56aff64bf
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: apps.deployment-descprod-descprod
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        cattle.io/timestamp: '2023-09-27T17:02:41Z'
        nersc.gov/collab_uids: ''
        nersc.gov/gid: '96594'
        nersc.gov/gids: 60152,57177,96414,96594
        nersc.gov/roles: user
        nersc.gov/uid: '96594'
        nersc.gov/username: dladams
      creationTimestamp: null
      labels:
        workload.user.cattle.io/workloadselector: apps.deployment-descprod-descprod
    spec:
      affinity: {}
      containers:
        - args:
            - git-safedir
            - update-desc-prod
            - mysql:noaio
            - force-https
            - server
          image: dladams/descprod:10
          imagePullPolicy: Always
          name: container-0
          resources: {}
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              add:
                - CHOWN
                - DAC_OVERRIDE
                - FOWNER
                - SETGID
                - SETUID
              drop:
                - ALL
            privileged: false
            readOnlyRootFilesystem: false
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /mnt/dpvol02
              name: vol-uyy4m
            - mountPath: /mnt/dpvol01
              name: vol-3dnhq
            - mountPath: /secrets
              name: volume-descprod-secrets
            - mountPath: /mnt/dpvol03
              name: vol-6vzal
            - mountPath: /var/lib/mysql
              name: vol-6vzal
              subPath: mysql
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
        - name: vol-3dnhq
          persistentVolumeClaim:
            claimName: dpvol01
        - name: vol-uyy4m
          persistentVolumeClaim:
            claimName: dpvol02
        - name: vol-6vzal
          persistentVolumeClaim:
            claimName: dpvol03
        - name: volume-descprod-secrets
          secret:
            defaultMode: 420
            secretName: descprod-secrets
status:
  availableReplicas: 1
  conditions:
    - lastTransitionTime: '2023-09-26T17:25:55Z'
      lastUpdateTime: '2023-09-26T17:25:55Z'
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: 'True'
      type: Available
    - lastTransitionTime: '2023-09-27T13:56:58Z'
      lastUpdateTime: '2023-09-27T17:02:46Z'
      message: ReplicaSet "descprod-6666b9c95" has successfully progressed.
      reason: NewReplicaSetAvailable
      status: 'True'
      type: Progressing
  observedGeneration: 78
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
