apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: '53'
    field.cattle.io/description: DESCprod web service
    field.cattle.io/publicEndpoints: >-
      [{"addresses":["128.55.206.106"],"port":80,"protocol":"HTTP","serviceName":"descprod:ingress-e9073a6bac7260568c05a661a5b2ab37","ingressName":"descprod:www","hostname":"www.descprod.org","allNodes":true},{"addresses":["128.55.206.106"],"port":30123,"protocol":"TCP","serviceName":"descprod:descprod-nodeport","allNodes":true},{"addresses":["128.55.206.106"],"port":30124,"protocol":"TCP","serviceName":"descprod:descprod-nodeport","allNodes":true},{"addresses":["128.55.206.106"],"port":80,"protocol":"HTTP","serviceName":"descprod:ingress-abb22350363dba5b6d6a88992a852fc8","ingressName":"descprod:www","hostname":"www.descprod.production.svc.spin.nersc.org","allNodes":true}]
    nersc.gov/collab_uids: 70781,73586,73749,75699,78540,99896
    nersc.gov/gid: '70981'
    nersc.gov/gids: 60152,57177,70981,76870,75699,96414,96719,99896
    nersc.gov/roles: user
    nersc.gov/uid: '70981'
    nersc.gov/username: heatherk
  creationTimestamp: '2023-09-22T18:42:04Z'
  generation: 320
  labels:
    workload.user.cattle.io/workloadselector: apps.deployment-descprod-descprod
  name: descprod
  namespace: descprod
  resourceVersion: '769195535'
  uid: fdbbef32-ce24-40be-bea8-62f56aff64bf
spec:
  paused: true
  progressDeadlineSeconds: 600
  replicas: 0
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: apps.deployment-descprod-descprod
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        cattle.io/timestamp: '2023-12-21T20:07:51Z'
        nersc.gov/collab_uids: 70781,73586,73749,75699,78540,99896
        nersc.gov/gid: '70981'
        nersc.gov/gids: 60152,57177,70981,76870,75699,96414,96719,99896
        nersc.gov/roles: user
        nersc.gov/uid: '70981'
        nersc.gov/username: heatherk
      creationTimestamp: null
      labels:
        workload.user.cattle.io/workloadselector: apps.deployment-descprod-descprod
    spec:
      affinity: {}
      containers:
        - args:
            - git-safedir
            - update-desc-prod
            - mysql:noaio
            - force-https
            - server
          image: dladams/descprod:10
          imagePullPolicy: Always
          name: container-0
          resources: {}
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              add:
                - CHOWN
                - DAC_OVERRIDE
                - FOWNER
                - SETGID
                - SETUID
              drop:
                - ALL
            privileged: false
            readOnlyRootFilesystem: false
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /mnt/dpvol02
              name: vol-uyy4m
            - mountPath: /mnt/dpvol01
              name: vol-3dnhq
            - mountPath: /secrets
              name: volume-descprod-secrets
            - mountPath: /mnt/dpvol03
              name: vol-6vzal
            - mountPath: /var/lib/mysql
              name: vol-6vzal
              subPath: mysql
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
        - name: vol-3dnhq
          persistentVolumeClaim:
            claimName: dpvol01
        - name: vol-uyy4m
          persistentVolumeClaim:
            claimName: dpvol02
        - name: vol-6vzal
          persistentVolumeClaim:
            claimName: dpvol03
        - name: volume-descprod-secrets
          secret:
            defaultMode: 420
            secretName: descprod-secrets
status:
  conditions:
    - lastTransitionTime: '2024-08-07T13:14:49Z'
      lastUpdateTime: '2024-08-07T13:14:49Z'
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: 'True'
      type: Available
    - lastTransitionTime: '2024-08-09T14:17:58Z'
      lastUpdateTime: '2024-08-09T14:17:58Z'
      message: Deployment is paused
      reason: DeploymentPaused
      status: Unknown
      type: Progressing
  observedGeneration: 320
