#!/bin/bash

# runapp-parsltest
#
# David Adams
# March 2023
#
# This is the deccprod application interface for parsltest.
# Usage: $0 CFG HFG
#   CFG is the string passed to desc-wfmon-parsltest
#   HFG is a configuration string searched for field ptenv:VER:LOC

STALOG=current-status.txt
MYNAME=$(basename $0)

function myecho() {
  echo $MYNAME: $*
  echo $MYNAME: $* >$STALOG
}

# Default params for setting up the env.
MYENV=ptenv
MYVER=00
MYLOC=hom

CFG=$1
HFG=${2:-$MYENV:$MYVER:$MYLOC}

if [ -z "$CFG" -o "$CFG" = "-h" ]; then
  echo Usage: $MYNAME CFG HFG
  echo "  CFG - Config passed to parsltest."
  echo "  HFG - Env setup taken from field ptenv:VER:LOC [$MYENV:$MYVER:$MYLOC]"
  exit 0
fi

myecho Config: $CFG
myecho Howfig: $HFG

# Parse the howfig to get the env params: ENV, VER, LOC
ENV=
VER=$MYVER
LOC=$MYLOC
if ! FIELDS=$(descprod-split-config $HFG); then
  myecho Invalid howfig: $HFG
  exit 1
fi
for FIELD in $FIELDS; do
  if ! VALS=($(descprod-split-config-field $FIELD)); then
    myecho Invalid howfig field: $FIELD
    exit 1
  fi
  NAM=${VALS[0]}
  if [ $NAM = ptenv ]; then
    ENV=$NAM
    VAL1=${VALS[1]}
    VAL2=${VALS[2]}
    if [ -n "$VAL1" ]; then
      VER=$VAL1
    fi
    if [ -n "$VAL2" ]; then
      LOC=$VAL2
    fi
  fi
done

if [ -z "$ENV" ]; then
  myecho Unable to deduce env from howfig $HFG
  exit 2
fi

if ! $ENV-find $LOC $VER; then
  myecho Creating env $ENV $VER $LOC.
  time $ENV-create $LOC $VER
  if ! $ENV-find $LOC $VER; then
    myecho "ERROR: Unable to create env $ENV $LOC $VER."
    exit 1
  fi
fi

echo
myecho Setting up env $ENV $VER $LOC
if ! source $ENV-setup $LOC $VER; then
  myecho "Unable to set up with $ENV-setup."
  exit 1
fi

echo
myecho Running parsltest with $CFG
desc-wfmon-parsltest $CFG
exit $?
