#!/bin/bash

# descprod-output-dir
#
# Return the base directory where descprod and its applications
# should write. This includes job directories and software
# installations.

MYNAME=$(basename $0)
OPT=${1:-create}
SUBDIR=${2}

if [[ $1 == -h ]]; then
  echo Usage: $MYNAME: [OPT [SUBDIR]]
  echo "  Where OPT [create] is any of the following"
  echo "       get - Return the directory name."
  echo "     check - Return the directory name if readable."
  echo "    create - Create directory if absent. Return directory if readable."
  echo "      list - display directory listing."
  echo "  The directory returned is the local DESCPprod output directory or or"
  echo "  its subdirectory SUBDIR if that value is provided."
  exit 0
fi

OUTDIR=$DESCPROD_OUTPUT_DIR
if [[ ! -n $OUTDIR ]]; then
  OUTDIR=${PSCRATCH:-${SCRATCH:-${HOME:-.}}}/descprod-out
fi
if [[ -n $SUBDIR ]]; then
  OUTDIR=$OUTDIR/$SUBDIR
fi

if [[ $OPT == list ]]; then
  ls -ls $OUTDIR/.
  exit $?
fi

if [[ $OPT == create ]]; then
  if [ ! -r $OUTDIR ]; then
    if mkdir -p $OUTDIR; then
      echo $MYNAME: Created $OUTDIR >&2
    else
      echo $MYNAME: ERROR: Unable to create $OUTDIR >&2
    fi
  fi
  OPT=check
fi

if [[ $OPT == check ]]; then
  if [ ! -r $OUTDIR ]; then
    echo $MYNAME: File not found: $OUTDIR. >&2
    exit 1
  fi
  OPT=get
fi

if [[ $OPT == get ]]; then
  echo $OUTDIR
else
  echo $MYNAME: Invalid option: $OPT
  exit 1
fi

