FROM ubuntu:latest
LABEL maintainer="David Adams dladams@bnl.gov"

RUN apt-get update
RUN apt-get install -y sudo
RUN apt-get install -y wget
RUN apt-get install -y curl
RUN apt-get install -y python3
RUN apt-get install -y python-is-python3
RUN apt-get install -y python3-pip
RUN apt-get install -y git
RUN apt-get install -y vim
RUN apt-get install -y nginx
RUN apt-get install -y net-tools
RUN apt-get install -y lsof

# Install conda
ENV CONDA_DIR /opt/conda
RUN wget --quiet https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O ~/miniconda.sh && \
    /bin/bash ~/miniconda.sh -b -p /opt/conda
ENV PATH=$CONDA_DIR/bin:$PATH

# Install work_queue
RUN conda install -y -c conda-forge ndcctools --no-deps

RUN pip install flask
RUN pip install parsl@git+https://github.com/parsl/parsl@desc#parsl[monitoring,workqueue]
RUN pip install git+https://github.com/LSSTDESC/desc-wfmon.git

RUN useradd -m descprod -g users -G sudo
RUN echo 'descprod ALL=NOPASSWD: ALL' >>/etc/sudoers
RUN chsh --shell /bin/bash descprod

USER descprod
WORKDIR /home/descprod
RUN mkdir .ssh
RUN mkdir bin
COPY nersc-proxy bin
