#!/bin/bash

# Read flags.
HELP=
ROOT=
while [ $# -gt 0 ]; do
  ARG=$1
  if [ ${ARG:0:2} = -- ]; then
    FLG=${ARG:2}
    shift
  else
    break
  fi
done

TAG=$1
shift
NAME=$(basename $(pwd))
FROM=$NAME:$TAG
CNAME=$NAME

# Create external directory.
EXTDIR=$HOME/desc/dpvol01
if [ ! -r $EXTDIR ]; then
  mkdir -p $EXTDIR
fi

echo Starting $CNAME with $FROM
docker run --name $CNAME --rm -p 3306:3306 -p 88:5000 -p 8888:8888 -v $EXTDIR:/mnt/dpvol01 -it $FROM $*

