#!/bin/bash

# runapp-parsltest
#
# David Adams
# March 2023
#
# This is the deccprod application interface for parsltest.
# Usage: $0 CFG HFG
#   CFG is the string passed to desc-wfmon-parsltest
#   HFG is a configuration string searched for field ptenv:VER:LOC

# Default params for setting up the env.
MYENV=ptenv
MYVER=00
MYLOC=home

MYNAME=$(basename $0)
CFG=$1
HFG=${2:-$MYENV:$MYVER:$MYLOC}

if [ -z "$CFG" -o "$CFG" = "-h" ]; then
  echo Usage: $MYNAME CFG HFG
  echo "  CFG - Config passed to parsltest."
  echo "  HFG - Env setup taken from field ptenv:VER:LOC [$MYENV:$MYVER:$MYLOC]"
  exit 0
fi

# Parse the howfig to get the env params: ENV, VER, LOC
ENV=
VER=$MYVER
LOC=$MYLOC
if ! FIELDS=$(descprod-split-config $HFG); then
  echo $MYNAME: Invalid howfig: $HFG
  exit 1
fi
for FIELD in $FIELDS; do
  if ! VALS=($(descprod-split-config-field $FIELD)); then
    echo $MYNAME: Invalid howfig field: $FIELD
    exit 1
  fi
  NAM=${VALS[0]}
  if [ $NAM = ptenv ]; then
    ENV=$NAM
    VAL1=${VALS[1]}
    VAL2=${VALS[2]}
    if [ -n "$VAL1" ]; then
      VER=$VAL1
    fi
    if [ -n "$VAL2" ]; then
      LOC=$VAL2
    fi
  fi
done

if [ -z "$ENV" ]; then
  echo MYNAME: Unable to deduce env from howfig $HFG
  exit 2
fi

if ! $ENV-find $LOC $VER; then
  echo $MYNAME: Creating env $ENV $VER $LOC.
  time $ENV-create $LOC $VER
  if ! $ENV-find $LOC $VER; then
    echo $MYNAME: ERROR: Creating env failed.
    exit 1
  fi
fi

echo
echo $MYNAME: Setting up env $ENV $VER $LOC
source $ENV-setup $LOC $VER

echo
echo $MYNAME: Running parsltest with $CFG
desc-wfmon-parsltest $CFG
exit $?
