#!/bin/bash

# runapp-parsltest
#
# David Adams
# March 2023
#
# This is the deccprod application interface for parsltest.

MYCFG=$1
MYLOC=${2:-home}
MYVER=${3:-00}

if ! ptenv-find $MYLOC $MYVER; then
  echo $MYNAME: Creating env.
  ptenv-create $MYLOC $MYVER
  if ! ptenv-find $MYLOC $MYVER; then
    echo $MYNAME: ERROR: Creating env failed.
    exit 1
  fi
fi

source ptenv-setup $MYLOC $MYVER

desc-wfmon-parsltest $MYCFG
exit $?
