#!/bin/bash

# worker-submit
#
# David Adams
# November 2022
#
# Slurm script to start a descprod worker.
#
# sbatch batch-worker

# If not called with sbatch, then build and call the batch script.
if [ -z "$SLURM_JOB_ID" ]; then

  NNOD=1
  TMIN=30
  OPT=$1
  shift
  RESUB=
  THIS=$(readlink -f $0)
  WKRDIR=$(dirname $THIS)
  SERVER=$($WKRDIR/worker-getip):$($WKRDIR/worker-port)
  echo SERVER=$SERVER
  QOS=regular
  if [ $TMIN -le 30 -a $NNOD -le 4 ]; then
    QOS=debug
  fi
  while [ -n "$OPT" ]; do
    VAL=$1
    shift
    if [ $OPT = -n ]; then
      if [ -z "$VAL" ]; then
        echo ERROR: Option $OPT requires an argument
        exit 1
      fi
      NNOD=$VAL
    elif [ $OPT = -t ]; then
      if [ -z "$VAL" ]; then
        echo ERROR: Option $OPT requires an argument
        exit 1
      fi
      TMIN=$VAL
    elif [ $OPT = -s ]; then
      if [ -z "$VAL" ]; then
        echo ERROR: Option $OPT requires an argument
        exit 1
      fi
      SERVER=$VAL
      echo SERVER=$SERVER
    elif [ $OPT = -q ]; then
      if [ -z "$VAL" ]; then
        echo ERROR: Option $OPT requires an argument
        exit 1
      fi
      QOS=$VAL
      echo QOS=$QOS
    else
      echo ERROR: Invalid flag: $OPT
      exit 1
    fi
    OPT=$1
    shift
  done
  
  NMIN=$((TMIN%60))
  if [ ${#NMIN} -lt 2 ]; then TMIN=0$TMIN; fi
  NHOU=$((TMIN/60))
  STIM=$NHOU:$NMIN:00

  BASDIR=/pscratch/sd/d/dladams/slurmout

  THIS=$(readlink -f $0)
  BFIL=$BASDIR/$(basename $THIS).sbatch
  echo '#!/bin/bash' > $BFIL
  echo >>$BFIL
  echo "#SBATCH --nodes=$NNOD" >>$BFIL
  echo "#SBATCH --time=$STIM" >>$BFIL
  echo "#SBATCH --constraint=cpu" >>$BFIL
  echo "#SBATCH --qos=$QOS" >>$BFIL
  echo "#SBATCH --account=m1727" >>$BFIL
  echo >>$BFIL
  echo 'if [ -z "$SLURM_JOB_ID" ]; then echo SLURM job ID is not set; exit 1; fi' >>$BFIL
  echo >>$BFIL
  echo "export SERVER=$SERVER" >> $BFIL
  mv $BFIL $BFIL.tmp
  cat $BFIL.tmp $THIS >$BFIL
  echo $(date): Submitting batch job with sbatch $BFIL
  cd $BASDIR
  sbatch $BFIL
  exit $?
fi

echo Start: $(date)
echo Host: $(hostname)

export TZ=UTC

CTIMEOUT=60
ITIMEOUT=10

PTELOC=scr
PTEVER=02

BASDIR=/pscratch/sd/d/dladams/slurmout
JOBDIR=$BASDIR/$SLURM_JOB_ID
mkdir $JOBDIR
cd $JOBDIR
set | grep SLURM_ slurmenv.log
NCORE=100
RUNDIR=$JOBDIR/run
mkdir $RUNDIR
echo $(date): Setting up ptenv $PTELOC $PTEVER.
. $HOME/desc/dev/desc-prod/ptenv/ptenv-setup $PTELOC $PTEVER
echo $(date) Starting workers for $SERVER
date > $RUNDIR/time-start
srun work_queue_worker --workdir=$JOBDIR/run --connect-timeout=$CTIMEOUT --idle-timeout=$ITIMEOUT --cores=$NCORE $SERVER
echo Worker exited at $(date)
date > $RUNDIR/time-stop
echo End: $(date)
