#!/bin/bash
#
# worker-local
#
# Start a worker on the server or any machine with env.

THIS=$(readlink -f $0)
NCORE=4
SERVER=localhost:9123

echo Starting worker for $SERVER
work_queue_worker --cores=$NCORE --timeout=60 $SERVER
